server:
  port: 8083

spring:
  application:
    name: ms-sensores

  rabbitmq:
    # AQUI: Variáveis para conectar no Rabbit
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ms-condominios:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

# Configurações de negócio (Filas)
app:
  rabbitmq:
    exchange: "alertas.v1.events"
    routing-key: "gerar-alerta"